language: csharp
solution: ./src/AppGregariaApi/AppGregariaApi.sln
mono: none
dotnet: 2.0.0
script:
  - dotnet restore ./src/AppGregariaApi/AppGregariaApi.sln
  - dotnet build ./src/AppGregariaApi/AppGregariaApi.sln